### ISSUE TITLE
200210_회의

### ISSUE THREAD

**Issue by pdache** [Hyeon9mak/AlgoITso#6]
### 교수님 피드백
- - -
1. 피부 트러블 정도 - 단계를 나누는 방법까지는 좋으나 정확한 트러블 정도를 나눌 수 있는 실제 값과 데이터베이스가 필요
2. 각질량 - 정확한 고가의 장비로 각질량 체크를 통한 데이터베이스를 만들고 우리의 생각과 실제 값을 비교하는 단계가 필요
3. 피부의 유수분 밸런스 체크 - 정확한 고가의 장비로 유수분 체크를 통한 데이터베이스를 만들고 조원들의 생각과 실값을 비교하는 단계가 필요

> - 데이터를 비교할 수 있는 표본을 찾아야하고 방법을 좀 더 구체화 할 것
> - 기존 기기들보다 정확한 값을 추출하거나 기존 기기들에서 참신한 기능을 추가할 것
- - -

위의 피드백을 통해 회의를 진행

- 현재 원거리로 유수분 밸런스를 측정할 수 있는 기술이 없음
->좀 더 아이디어를 구체화 할 필요가 있음
- 트러블 정도
->정확한 데이터베이스가 없기 때문에 트러블에 대한 표준을 찾아야 함
- 각질량
->논문들과 데이터베이스가 있기 때문에 우리의 기술과 실제 논문, 기기들을 비교했을 때 값의 오차가 없거나 매우 작아야 함

**Comment by Hyeon9mak** [comment]
확인! 회의기록으로 남기겠음

**Comment by Hyeon9mak** [comment]
회의기록/2020-02-11-회의기록.md 에 작성해뒀음
